# permissions to do viewer maprtickets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maprticket-viewer-role
rules:
- apiGroups:
  - nsc.k8s.io
  resources:
  - maprtickets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nsc.k8s.io
  resources:
  - maprtickets/status
  verbs:
  - get
