kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample
  namespace: sample
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: pgroup
- kind: ServiceAccount
  name: default
  namespace: sample
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
